export const bangs = [
  // AI Apps
  {
    c: "AI",
    d: "www.chatgpt.com",
    r: 0,
    s: "ChatGPT",
    sc: "AI",
    t: ["ai", "gpt","chatgpt"],
    u: "https://www.chatgpt.com/search?q={{{s}}}",
  },
  {
    c: "AI",
    d: "www.grok.com",
    r: 0,
    s: "Grok",
    sc: "AI",
    t: "grok",
    u: "https://grok.com/chat?q={{{s}}}",
  },
  // Social Media
  {
    c: "Online Services",
    d: "twitter.com",
    r: 9964,
    s: "Twitter",
    sc: "Social",
    t: ["x", "tw", "twt", "twtr", "twitter"],
    u: "https://twitter.com/search?q={{{s}}}",
  },
  {
    c: "Online Services",
    d: "twitter.com",
    r: 0,
    s: "Twitter users",
    sc: "Social",
    t: "twuser",
    u: "https://twitter.com/search/users?q={{{s}}}",
  },
  {
    c: "Online Services",
    d: "www.reddit.com",
    r: 40882,
    s: "Reddit",
    sc: "Social",
    t: ["r", "reddit"],
    u: "https://www.reddit.com/search?q={{{s}}}",
  },
  {
    c: "Entertainment",
    d: "reddit.com",
    r: 10750,
    s: "Reddit",
    sc: "Forum",
    t: "sr",
    u: "http://reddit.com/r/{{{s}}}",
  },
  {
    c: "Online Services",
    d: "www.linkedin.com",
    r: 3073,
    s: "LinkedIn",
    sc: "Social",
    t: ["li", "linkedin"],
    u: "https://www.linkedin.com/search/results/all/?keywords={{{s}}}",
  },
  // Programming
  {
    c: "Tech",
    d: "github.com",
    r: 15975,
    s: "GitHub",
    sc: "Programming",
    t: ["gh", "github"],
    u: "https://github.com/search?utf8=%E2%9C%93&q={{{s}}}",
  },
  // Search Engine
  {
    c: "Online Services",
    d: "www.google.com",
    r: 1942262,
    s: "Google",
    sc: "Google",
    t: ["g", "gg", "google"],
    u: "https://www.google.com/search?q={{{s}}}",
  },
  {
    c: "Online Services",
    d: "google.com",
    r: 52329,
    s: "Google Images",
    sc: "Google",
    t: ["gi", "gimg", "gimages"],
    u: "https://google.com/search?tbm=isch&q={{{s}}}&tbs=imgo:1",
  },
  {
    c: "Online Services",
    d: "google.com",
    r: 55096,
    s: "Google Maps",
    sc: "Maps",
    t: ["gm", "gmaps"],
    u: "https://google.com/maps/place/{{{s}}}",
  },
  // Shopping
  {
    c: "Shopping",
    d: "www.flipkart.com",
    r: 126,
    s: "Flipkart",
    sc: "Online",
    t: "fk",
    u: "http://www.flipkart.com/search?q={{{s}}} ",
  },
  {
    c: "Shopping",
    d: "www.amazon.com",
    r: 0,
    s: "Amazon",
    sc: "Online",
    t: ["am", "amz", "amzn", "amazon" ],
    u: "https://www.amazon.in/s?k={{{s}}}",
  },
];