name: Daily fetch bangs.json from Kagi
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  fetch-bangs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install bun
        uses: oven-sh/setup-bun@v1

      - name: Download bangs.json
        run: |
          curl -o bangs.json https://raw.githubusercontent.com/kagisearch/bangs/refs/heads/main/data/bangs.json

      - name: Verify file
        run: |
          if [ ! -s bangs.json ]; then
            echo "Downloaded file is empty"
            exit 1
          fi
          if ! jq empty bangs.json; then
            echo "Downloaded file is not valid JSON"
            exit 1
          fi

      - name: Replace bangs.json
        run: |
          mkdir -p src
          mv bangs.json src/bangs/bangs.json

      - name: 🥔 hash
        run: bun run hash

      - name: Commit changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add src/bangs/bangs.json src/bangs/hashbang.ts
          git commit -m "chore: update bangs.json" || exit 0
          git push

      - name: Tailscale
        uses: tailscale/github-action@v3
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci

      - name: Add remote
        run: git remote add tangled git@ember:did:plc:krxbvxvis5skq7jj6eot23ul/unduckified

      - name: Configure ssh
        run: |
          mkdir -p ~/.ssh
          echo "StrictHostKeyChecking no" >> ~/.ssh/config

      - name: Push to tangled
        run: git push tangled main
