import { type Bang } from "./types";

export const bangs: Bang[] = [
    {
        c: "AI",
        d: "www.t3.chat",
        r: 0,
        s: "T3 Chat",
        sc: "AI",
        t: "t3",
        u: "https://www.t3.chat/new?q={{{s}}}",
        sb: [
            { b: "s", u: "search", l: 0, v: "true" },
            { b: "gpt-img", u: "model", l: 0, v: "gpt-image-1" },
            { b: "2.0-f", u: "model", l: 0, v: "gemini-2.0-flash" },
            {
                b: "2.0-fl",
                u: "model",
                l: 0,
                v: "gemini-2.0-flash-lite-preview-02-05",
            },
            { b: "2.5-f", u: "model", l: 0, v: "gemini-2.5-flash" },
            {
                b: "2.5-ft",
                u: "model",
                l: 0,
                v: "gemini-2.5-flash-thinking",
            },
            { b: "2.5-p", u: "model", l: 0, v: "gemini-2.5-pro" },
            { b: "4o-m", u: "model", l: 0, v: "gpt-4o-mini" },
            { b: "4o", u: "model", l: 0, v: "gpt-4o" },
            { b: "4.1", u: "model", l: 0, v: "gpt-4.1" },
            { b: "4.1-m", u: "model", l: 0, v: "gpt-4.1-mini" },
            { b: "4.1-n", u: "model", l: 0, v: "gpt-4.1-nano" },
            { b: "o3-m", u: "model", l: 0, v: "gpt-o3-mini" },
            { b: "o4-m", u: "model", l: 0, v: "gpt-o4-mini" },
            { b: "3.5", u: "model", l: 0, v: "claude-3.5" },
            { b: "3.7", u: "model", l: 0, v: "claude-3.7" },
            { b: "3.7r", u: "model", l: 0, v: "claude-3.7-reasoning" },
            { b: "g-3.3", u: "model", l: 0, v: "llama-3.3-70b-groq" },
            { b: "4s", u: "model", l: 0, v: "llama-4-scout" },
            { b: "4m", u: "model", l: 0, v: "llama-4-maverick" },
            { b: "v3f", u: "model", l: 0, v: "deepseek-v3-fireworks" },
            { b: "v3c", u: "model", l: 0, v: "deepseek-chat-v3-0324" },
            { b: "r1o", u: "model", l: 0, v: "deepseek-r1-openrouter" },
            { b: "r1g", u: "model", l: 0, v: "deepseek-r1-groq" },
            { b: "r1q", u: "model", l: 0, v: "deepseek-r1-distill-qwen-32b" },
            { b: "gv3", u: "model", l: 0, v: "grok-v3" },
            { b: "gv3-m", u: "model", l: 0, v: "grok-v3-mini" },
            { b: "32b", u: "model", l: 0, v: "qwq-32b" },
            { b: "4.5", u: "model", l: 0, v: "gpt-4.5" },
        ],
    },
];
