export const bangs = [
    {
        d: "www.apertium.org",
        r: 0,
        s: "https://www.apertium.org",
        t: "anlaf",
        u: "https://www.apertium.org/index.eng.html?dir=nld-afr&q={{{s}}}",
        sb: [],
    },
    {
        d: "wiki.apertium.org",
        r: 0,
        s: "Appertium",
        t: "apertium",
        u: "http://wiki.apertium.org/w/index.php?title=Special:Search&search={{{s}}}&go=Go",
        sb: [],
    },
    {
        d: "dict.tu-chemnitz.de",
        r: 4,
        s: "Beolingus De-en",
        t: "beo",
        u: "http://dict.tu-chemnitz.de/dings.cgi?service=deen&query={{{s}}}",
        sb: [],
    },
    {
        d: "dict.tu-chemnitz.de",
        r: 0,
        s: "Beolingus De-es",
        t: "beoes",
        u: "http://dict.tu-chemnitz.de/dings.cgi?service=dees&query={{{s}}}",
        sb: [],
    },
    {
        d: "dict.tu-chemnitz.de",
        r: 0,
        s: "Beolingus De-pt",
        t: "beopt",
        u: "http://dict.tu-chemnitz.de/dings.cgi?service=dept&query={{{s}}}",
        sb: [],
    },
    {
        d: "www.blocket.se",
        r: 11,
        s: "Blocket",
        t: "blocket",
        u: "http://www.blocket.se/hela_sverige?q={{{s}}}&cg=0&w=3&st=s&st=u&st=b&ca=11&l=0&md=th",
        sb: [],
    },
    {
        d: "www.conferenceranks.com",
        r: 0,
        s: "Conference Ranks",
        t: "confranks",
        u: "http://www.conferenceranks.com/?searchall={{{s}}}",
        sb: [],
    },
    {
        d: "www.dict.cc",
        r: 1892,
        s: "dict.cc",
        t: "dcc",
        u: "http://www.dict.cc/?s={{{s}}}",
        sb: [],
    },
    {
        d: "www.yelp.com",
        r: 0,
        s: "Yelp Delivery Search",
        t: "delivery",
        u: "http://www.yelp.com/search?&rpp=10&find_loc=&start=0&attrs=RestaurantsDelivery&find_desc={{{s}}}",
        sb: [],
    },
    {
        d: "www.google.com",
        r: 0,
        s: "google alerts",
        t: "galerts",
        u: "https://www.google.com/alerts?q={{{s}}}",
        sb: [],
    },
    {
        d: "hollowknight.wikia.com",
        r: 0,
        s: "Hollow Knight Wikia",
        t: "hkwikia",
        u: "http://hollowknight.wikia.com/wiki/Special:Search?search={{{s}}}&fulltext=Search&ns0=1&ns14=1",
        sb: [],
    },
    {
        d: "hud.summon.serialssolutions.com",
        r: 0,
        s: "University of Huddersfield Library",
        t: "hud",
        u: "https://hud.summon.serialssolutions.com/search?ho=t&l=en&fvf=ContentType%2CBook+Review%2Ct&q={{{s}}}&limit=everything",
        sb: [],
    },
    {
        d: "www.ricerca24.ilsole24ore.com",
        r: 0,
        s: "Il Sole 24 Ore",
        t: "ilsole24ore",
        u: "http://www.ricerca24.ilsole24ore.com/fc?keyWords={{{s}}}&sbmit=+&header-search=keyWords&cmd=static&moneyPath=http://finanza-mercati.ilsole24ore.com&chId=30&path=/search/search_engine.jsp&field=Titolo|Testo&orderBy=score+desc",
        sb: [],
    },
    {
        d: "www.swahili.it",
        r: 0,
        s: "Vocabolario Italiano-Esperanto (Minnaja)",
        t: "iteo",
        u: "http://www.swahili.it/glossword/index.php?a=term&d=2&q={{{s}}}",
        sb: [],
    },
    {
        d: "dict.leo.org",
        r: 5,
        s: "LEO Dictionary Chinese",
        t: "leoc",
        u: "http://dict.leo.org/chde?lp=chde&search={{{s}}}",
        sb: [],
    },
    {
        d: "dict.leo.org",
        r: 364,
        s: "LEO Dictionary English",
        t: "leoe",
        u: "http://dict.leo.org/ende?lp=ende&search={{{s}}}",
        sb: [],
    },
    {
        d: "dict.leo.org",
        r: 84,
        s: "LEO Dictionary French",
        t: "leof",
        u: "http://dict.leo.org/frde?lp=frde&search={{{s}}}",
        sb: [],
    },
    {
        d: "dict.leo.org",
        r: 35,
        s: "LEO Dictionary Italian",
        t: "leoi",
        u: "http://dict.leo.org/itde?lp=itde&search={{{s}}}",
        sb: [],
    },
    {
        d: "dict.leo.org",
        r: 5,
        s: "LEO Dictionary Russian",
        t: "leor",
        u: "http://dict.leo.org/rude?lp=rude&search={{{s}}}",
        sb: [],
    },
    {
        d: "dict.leo.org",
        r: 90,
        s: "LEO Dictionary Spanish",
        t: "leos",
        u: "http://dict.leo.org/esde?lp=esde&search={{{s}}}",
        sb: [],
    },
    {
        d: "listado.mercadolibre.com.mx",
        r: 7,
        s: "Mercadolibre México",
        t: "mercadolibremx",
        u: "https://listado.mercadolibre.com.mx/{{{s}}}",
        sb: [],
    },
    {
        d: "listado.mercadolibre.com.mx",
        r: 134,
        s: "Mercado Libre Mexico",
        t: "mlmx",
        u: "https://listado.mercadolibre.com.mx/{{{s}}}",
        sb: [],
    },
    {
        d: "mobile.wunderground.com",
        r: 0,
        s: "Mobile Weather Underground",
        t: "mwu",
        u: "http://mobile.wunderground.com/q/{{{s}}}",
        sb: [],
    },
    {
        d: "www.yelp.com",
        r: 0,
        s: "Yelp Open Search",
        t: "open",
        u: "http://www.yelp.com/search?find_desc=&ns=1#start=0&open_now=2510",
        sb: [],
    },
    {
        d: "mobile.pons.com",
        r: 0,
        s: "Pons",
        t: "ponsge",
        u: "https://mobile.pons.com/dict/search/mobile-results/?q={{{s}}}&l=deen",
        sb: [],
    },
    {
        d: "community.sophos.com",
        r: 0,
        s: "Sophos Community",
        t: "sophoskb",
        u: "https://community.sophos.com/search?q={{{s}}}",
        sb: [],
    },
    {
        d: "tyda.se",
        r: 63,
        s: "Tyda.se",
        t: "tyda",
        u: "http://tyda.se/search?w={{{s}}}",
        sb: [],
    },
    {
        d: "duckduckgo.com",
        r: 0,
        s: "UNHCR",
        t: "unhcr",
        u: "https://duckduckgo.com/?q={{{s}}}+site:http://www.unhcr.org/",
        sb: [],
    },
    {
        d: "www.vandale.nl",
        r: 48,
        s: "Van Dale",
        t: "vandale",
        u: "http://www.vandale.nl/opzoeken?pattern={{{s}}}&lang=nn",
        sb: [],
    },
    {
        d: "www.watchcount.com",
        r: 0,
        s: "WatchCount.com",
        t: "watchcount",
        u: "http://www.watchcount.com/completed.php?bkw={{{s}}}&bcat=0&bcts=&sfsb=Show+Me%21&csbin=all&cssrt=ts&bslr=&bnp=&bxp=",
        sb: [],
    },
];
